/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author b4st4rd
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        bRegistrar = new javax.swing.JButton();
        bIngresar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNombre = new javax.swing.JTextField();
        txTelefono = new javax.swing.JTextField();
        txOcupacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        bRegistrar1 = new javax.swing.JButton();
        bCancelarR = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        panelCuenta = new javax.swing.JPanel();
        bConsignar = new javax.swing.JButton();
        bActivarC = new javax.swing.JButton();
        bDesactivarC = new javax.swing.JButton();
        bRetirar = new javax.swing.JButton();
        bSalirC = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        labSaldo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelRegistro1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txContraseña1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bAceptarR = new javax.swing.JButton();
        txContraseña = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        bElegirC = new javax.swing.JButton();
        bCrearC = new javax.swing.JButton();
        bCualesC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        bSalir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        panelIngreso = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txIDing = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txContraseñaIng = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        bIngresarI = new javax.swing.JButton();
        bCancelarI = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        panelCreaCuenta = new javax.swing.JPanel();
        bCancelarC2 = new javax.swing.JButton();
        bAhorros = new javax.swing.JButton();
        bCorriente = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        panelIngresoCuenta = new javax.swing.JPanel();
        bCancelarIC = new javax.swing.JButton();
        bIngresarC2 = new javax.swing.JButton();
        txCuentaIng = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelOperacion = new javax.swing.JPanel();
        txOperacion = new javax.swing.JTextField();
        bOperacion = new javax.swing.JButton();
        bCancelarO = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StarBank");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicial.setBackground(new java.awt.Color(255, 255, 255));
        panelInicial.setPreferredSize(new java.awt.Dimension(400, 300));
        panelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bRegistrar.setBackground(new java.awt.Color(255, 220, 220));
        bRegistrar.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bRegistrar.setForeground(new java.awt.Color(1, 1, 1));
        bRegistrar.setText("Registrar");
        bRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelInicial.add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 137, 95, -1));

        bIngresar.setBackground(new java.awt.Color(255, 220, 220));
        bIngresar.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bIngresar.setForeground(new java.awt.Color(1, 1, 1));
        bIngresar.setText("Ingresar");
        bIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelInicial.add(bIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 137, 95, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelInicial.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(panelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 516));

        panelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistro.setPreferredSize(new java.awt.Dimension(400, 300));
        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Nombre completo");
        panelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 44, 170, 26));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("ID");
        panelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 44, 170, 26));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Telefono");
        panelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 116, 170, 26));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Ocupación");
        panelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 116, 170, 26));

        txID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txIDKeyTyped(evt);
            }
        });
        panelRegistro.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 76, 170, -1));
        panelRegistro.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 76, 170, -1));
        panelRegistro.add(txTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, 170, -1));
        panelRegistro.add(txOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 148, 170, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REGISTRO");
        jLabel5.setToolTipText("");
        panelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 6, 170, 26));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dirección");
        panelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 188, 170, 26));
        panelRegistro.add(txDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 220, 352, 31));

        bRegistrar1.setBackground(new java.awt.Color(255, 220, 220));
        bRegistrar1.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bRegistrar1.setForeground(new java.awt.Color(1, 1, 1));
        bRegistrar1.setText("Registrar");
        bRegistrar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelRegistro.add(bRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 257, 95, -1));

        bCancelarR.setBackground(new java.awt.Color(255, 220, 220));
        bCancelarR.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bCancelarR.setForeground(new java.awt.Color(1, 1, 1));
        bCancelarR.setText("Cancelar");
        bCancelarR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelRegistro.add(bCancelarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 257, 95, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelRegistro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, 516));

        panelCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelCuenta.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bConsignar.setBackground(new java.awt.Color(255, 220, 220));
        bConsignar.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bConsignar.setForeground(new java.awt.Color(1, 1, 1));
        bConsignar.setText("Consignar");
        bConsignar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCuenta.add(bConsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 131, 135, -1));

        bActivarC.setBackground(new java.awt.Color(255, 220, 220));
        bActivarC.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bActivarC.setForeground(new java.awt.Color(1, 1, 1));
        bActivarC.setText("Activar cuenta");
        bActivarC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCuenta.add(bActivarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, 170, -1));

        bDesactivarC.setBackground(new java.awt.Color(255, 220, 220));
        bDesactivarC.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bDesactivarC.setForeground(new java.awt.Color(1, 1, 1));
        bDesactivarC.setText("Desactivar cuenta");
        bDesactivarC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCuenta.add(bDesactivarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 212, 170, -1));

        bRetirar.setBackground(new java.awt.Color(255, 220, 220));
        bRetirar.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bRetirar.setForeground(new java.awt.Color(1, 1, 1));
        bRetirar.setText("Retirar");
        bRetirar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCuenta.add(bRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 131, 135, -1));

        bSalirC.setBackground(new java.awt.Color(255, 220, 220));
        bSalirC.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bSalirC.setForeground(new java.awt.Color(1, 1, 1));
        bSalirC.setText("Salir");
        bSalirC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCuenta.add(bSalirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 95, -1));

        jLabel19.setText("Saldo actual:");
        panelCuenta.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));
        panelCuenta.add(labSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelCuenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelRegistro1.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Ingresa una contraseña");
        panelRegistro1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 190, 26));
        panelRegistro1.add(txContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Confirmar contraseña");
        panelRegistro1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 155, 180, 26));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REGISTRO");
        jLabel9.setToolTipText("");
        panelRegistro1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 12, 170, 26));

        bAceptarR.setBackground(new java.awt.Color(255, 220, 220));
        bAceptarR.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bAceptarR.setForeground(new java.awt.Color(1, 1, 1));
        bAceptarR.setText("Aceptar");
        bAceptarR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelRegistro1.add(bAceptarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 249, 95, -1));
        panelRegistro1.add(txContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelRegistro1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(panelRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        panelCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bElegirC.setBackground(new java.awt.Color(255, 220, 220));
        bElegirC.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bElegirC.setForeground(new java.awt.Color(1, 1, 1));
        bElegirC.setText("Elegir cuenta");
        bElegirC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCliente.add(bElegirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 55, 170, -1));

        bCrearC.setBackground(new java.awt.Color(255, 220, 220));
        bCrearC.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bCrearC.setForeground(new java.awt.Color(1, 1, 1));
        bCrearC.setText("Crear cuenta");
        bCrearC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCliente.add(bCrearC, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 12, 170, -1));

        bCualesC.setBackground(new java.awt.Color(255, 220, 220));
        bCualesC.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bCualesC.setForeground(new java.awt.Color(1, 1, 1));
        bCualesC.setText("¿Cuales son mis cuentas?");
        bCualesC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCliente.add(bCualesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 104, 230, -1));

        jScrollPane1.setViewportView(jTextPane1);

        panelCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 167, 230, 80));

        bSalir.setBackground(new java.awt.Color(255, 220, 220));
        bSalir.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bSalir.setForeground(new java.awt.Color(1, 1, 1));
        bSalir.setText("Salir");
        bSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCliente.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 95, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelCliente.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelIngreso.setBackground(new java.awt.Color(255, 255, 255));
        panelIngreso.setPreferredSize(new java.awt.Dimension(400, 300));
        panelIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 1, 1));
        jLabel10.setText("Documento (ID)");
        panelIngreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 26));

        txIDing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txIDingKeyTyped(evt);
            }
        });
        panelIngreso.add(txIDing, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, 31));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 1, 1));
        jLabel11.setText("Contraseña");
        panelIngreso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 26));
        panelIngreso.add(txContraseñaIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(1, 1, 1));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("INGRESAR");
        jLabel12.setToolTipText("");
        panelIngreso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 26));

        bIngresarI.setBackground(new java.awt.Color(255, 220, 220));
        bIngresarI.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bIngresarI.setForeground(new java.awt.Color(1, 1, 1));
        bIngresarI.setText("Ingresar");
        bIngresarI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelIngreso.add(bIngresarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 95, -1));

        bCancelarI.setBackground(new java.awt.Color(255, 220, 220));
        bCancelarI.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bCancelarI.setForeground(new java.awt.Color(1, 1, 1));
        bCancelarI.setText("Cancelar");
        bCancelarI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelIngreso.add(bCancelarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 95, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelIngreso.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelCreaCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelCreaCuenta.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCreaCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCancelarC2.setBackground(new java.awt.Color(255, 220, 220));
        bCancelarC2.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bCancelarC2.setForeground(new java.awt.Color(1, 1, 1));
        bCancelarC2.setText("Cancelar");
        bCancelarC2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCreaCuenta.add(bCancelarC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 95, -1));

        bAhorros.setBackground(new java.awt.Color(255, 220, 220));
        bAhorros.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bAhorros.setForeground(new java.awt.Color(1, 1, 1));
        bAhorros.setText("Ahorros");
        bAhorros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCreaCuenta.add(bAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, 40));

        bCorriente.setBackground(new java.awt.Color(255, 220, 220));
        bCorriente.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bCorriente.setForeground(new java.awt.Color(1, 1, 1));
        bCorriente.setText("Corriente");
        bCorriente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelCreaCuenta.add(bCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelCreaCuenta.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(panelCreaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelIngresoCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoCuenta.setMinimumSize(new java.awt.Dimension(400, 300));
        panelIngresoCuenta.setPreferredSize(new java.awt.Dimension(400, 300));
        panelIngresoCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCancelarIC.setBackground(new java.awt.Color(255, 220, 220));
        bCancelarIC.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bCancelarIC.setForeground(new java.awt.Color(1, 1, 1));
        bCancelarIC.setText("Cancelar");
        bCancelarIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelIngresoCuenta.add(bCancelarIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 257, 95, -1));

        bIngresarC2.setBackground(new java.awt.Color(255, 220, 220));
        bIngresarC2.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bIngresarC2.setForeground(new java.awt.Color(1, 1, 1));
        bIngresarC2.setText("Ingresar");
        bIngresarC2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelIngresoCuenta.add(bIngresarC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 166, 140, -1));

        txCuentaIng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCuentaIngKeyTyped(evt);
            }
        });
        panelIngresoCuenta.add(txCuentaIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 132, 170, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 1, 1));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Numero de cuenta");
        panelIngresoCuenta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 100, 170, 26));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelIngresoCuenta.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelIngresoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelOperacion.setBackground(new java.awt.Color(255, 255, 255));
        panelOperacion.setPreferredSize(new java.awt.Dimension(400, 300));
        panelOperacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txOperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txOperacionKeyTyped(evt);
            }
        });
        panelOperacion.add(txOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 132, 272, -1));

        bOperacion.setBackground(new java.awt.Color(255, 220, 220));
        bOperacion.setFont(new java.awt.Font("Mukti Narrow", 0, 18)); // NOI18N
        bOperacion.setForeground(new java.awt.Color(1, 1, 1));
        bOperacion.setText("Consig-Retir");
        bOperacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelOperacion.add(bOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 166, 140, -1));

        bCancelarO.setBackground(new java.awt.Color(255, 220, 220));
        bCancelarO.setFont(new java.awt.Font("Mukti Narrow", 0, 14)); // NOI18N
        bCancelarO.setForeground(new java.awt.Color(1, 1, 1));
        bCancelarO.setText("Cancelar");
        bCancelarO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120), new java.awt.Color(255, 120, 120)));
        panelOperacion.add(bCancelarO, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 257, 95, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/png.png"))); // NOI18N
        panelOperacion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIDKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txIDKeyTyped

    private void txIDingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIDingKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txIDingKeyTyped

    private void txCuentaIngKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCuentaIngKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txCuentaIngKeyTyped

    private void txOperacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txOperacionKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txOperacionKeyTyped

    public static void notificar(String notificacion){
        JOptionPane.showMessageDialog(null, notificacion, "ATENCION", JOptionPane.ERROR_MESSAGE);
    }
    
    public static int confirmacion(String notificacion){
        return JOptionPane.showConfirmDialog(null, notificacion, "ATENCION", JOptionPane.YES_NO_OPTION);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bAceptarR;
    public javax.swing.JButton bActivarC;
    public javax.swing.JButton bAhorros;
    public javax.swing.JButton bCancelarC2;
    public javax.swing.JButton bCancelarI;
    public javax.swing.JButton bCancelarIC;
    public javax.swing.JButton bCancelarO;
    public javax.swing.JButton bCancelarR;
    public javax.swing.JButton bConsignar;
    public javax.swing.JButton bCorriente;
    public javax.swing.JButton bCrearC;
    public javax.swing.JButton bCualesC;
    public javax.swing.JButton bDesactivarC;
    public javax.swing.JButton bElegirC;
    public javax.swing.JButton bIngresar;
    public javax.swing.JButton bIngresarC2;
    public javax.swing.JButton bIngresarI;
    public javax.swing.JButton bOperacion;
    public javax.swing.JButton bRegistrar;
    public javax.swing.JButton bRegistrar1;
    public javax.swing.JButton bRetirar;
    public javax.swing.JButton bSalir;
    public javax.swing.JButton bSalirC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane jTextPane1;
    public javax.swing.JLabel labSaldo;
    public javax.swing.JPanel panelCliente;
    public javax.swing.JPanel panelCreaCuenta;
    public javax.swing.JPanel panelCuenta;
    public javax.swing.JPanel panelIngreso;
    public javax.swing.JPanel panelIngresoCuenta;
    public javax.swing.JPanel panelInicial;
    public javax.swing.JPanel panelOperacion;
    public javax.swing.JPanel panelRegistro;
    public javax.swing.JPanel panelRegistro1;
    public javax.swing.JPasswordField txContraseña;
    public javax.swing.JPasswordField txContraseña1;
    public javax.swing.JPasswordField txContraseñaIng;
    public javax.swing.JTextField txCuentaIng;
    public javax.swing.JTextField txDireccion;
    public javax.swing.JTextField txID;
    public javax.swing.JTextField txIDing;
    public javax.swing.JTextField txNombre;
    public javax.swing.JTextField txOcupacion;
    public javax.swing.JTextField txOperacion;
    public javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables
}
